version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --lower_case_table_names=1
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=study
      - MYSQL_PASSWORD=hard
      - MYSQL_DATABASE=base
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-proot",  "ping", "-h", "localhost"]
      interval: 10s
      timeout: 2s
      retries: 5