# default environment
spring:
  jmx:
    enabled: false
  flyway:
    enabled: false
  profiles:
    active: local
  groovy:
    template:
      check-template-location: false

scheduler:
  update:
    pattern: 0 0 0/1 * * ?

# local environment
---
server:
  port: 8080

spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: study
    password: hard
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

# production environment
---
server:
  port: 8080

spring:
  profiles: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: study
    password: hard
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
debug: true
